name: build

on:
  push:
    branches:
      - master
    paths-ignore:
      - .gitignore
      - README.md
  pull_request:
    paths-ignore:
      - .gitignore
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.15]
    name: Build with ${{ matrix.go }}

    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test -vet=off -race -coverprofile=coverage.txt -covermode=atomic ./...
